name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Get sources
      uses: actions/checkout@v1
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build static assets
      run: npm run build
